return {
    Name = "Aqua",
    Accent = Color3.fromRGB(0, 200, 180),  -- สีที่ใกล้เคียงกับสีเขียวอมฟ้าในโลโก้
    AcrylicMain = Color3.fromRGB(10, 30, 30),  -- สีเข้มให้ความรู้สึกลึกลับและเข้ากับสีโลโก้
    AcrylicBorder = Color3.fromRGB(40, 120, 100),  -- สีขอบที่เข้ากับโทนสีเขียวอมฟ้า
    AcrylicGradient = ColorSequence.new(Color3.fromRGB(0, 180, 150), Color3.fromRGB(0, 100, 90)),  -- ไล่สีตามโทนของโลโก้
    AcrylicNoise = 0.85,  -- ลดความชัดเจนของ Noise เพื่อให้ดูเรียบขึ้น
    TitleBarLine = Color3.fromRGB(50, 170, 150),  -- สีที่เข้ากับโทนโลโก้เพื่อให้ดูเด่น
    Tab = Color3.fromRGB(120, 200, 180),  -- สีของ Tab ที่เข้ากับโทนสีฟ้าและเขียว
    Element = Color3.fromRGB(80, 180, 160),  -- สีของ Element ที่เข้ากับธีมโลโก้
    ElementBorder = Color3.fromRGB(30, 80, 70),  -- ขอบของ Element ที่เข้มขึ้นเพื่อเน้นความคมชัด
    InElementBorder = Color3.fromRGB(60, 140, 120),  -- ขอบภายในที่มีสีเข้มขึ้น
    ElementTransparency = 0.75,  -- ลดความโปร่งใสเพื่อให้ดูเข้มขึ้น
    ToggleSlider = Color3.fromRGB(80, 180, 160),  -- สีของ Toggle ที่เข้ากับโทนสีหลักของโลโก้
    ToggleToggled = Color3.fromRGB(0, 120, 110),  -- สีเมื่อ Toggle ถูกเปิดเพื่อให้ดูสอดคล้องกับสีหลัก
    SliderRail = Color3.fromRGB(80, 180, 160),  -- สีของ Slider Rail ที่เข้ากับธีม
    DropdownFrame = Color3.fromRGB(100, 200, 180),  -- สีของ Dropdown Frame ที่ดูสะอาดและเรียบง่าย
    DropdownHolder = Color3.fromRGB(20, 70, 60),  -- สีของ Holder ที่เข้มเพื่อให้โดดเด่น
    DropdownBorder = Color3.fromRGB(20, 60, 55),  -- สีของขอบ Dropdown ที่เข้มเพื่อความสวยงาม
    DropdownOption = Color3.fromRGB(80, 180, 160),  -- สีของตัวเลือก Dropdown ที่เข้ากับธีม
    Keybind = Color3.fromRGB(80, 180, 160),  -- สีของ Keybind ที่สอดคล้องกับธีม
    Input = Color3.fromRGB(80, 180, 160),  -- สีของ Input ที่เข้มขึ้นเพื่อความคมชัด
    InputFocused = Color3.fromRGB(10, 50, 40),  -- สีเมื่อ Input โฟกัส ให้ความรู้สึกลึกลับและเข้ากับธีม
    InputIndicator = Color3.fromRGB(100, 200, 180),  -- สีที่เข้มขึ้นสำหรับ Indicator เพื่อความโดดเด่น
    Dialog = Color3.fromRGB(20, 70, 60),  -- สีของ Dialog ที่เข้มเพื่อให้ดูเข้ากับธีม
    DialogHolder = Color3.fromRGB(10, 60, 50),  -- สีของ Holder ที่เข้มขึ้นเพื่อให้ดูเท่
    DialogHolderLine = Color3.fromRGB(10, 50, 40),  -- สีของเส้นใน Dialog ที่เข้มเพื่อความแตกต่าง
    DialogButton = Color3.fromRGB(20, 70, 60),  -- สีของปุ่ม Dialog ที่เข้ากับธีม
    DialogButtonBorder = Color3.fromRGB(60, 140, 120),  -- สีของขอบปุ่มที่เข้มเพื่อความคมชัด
    DialogBorder = Color3.fromRGB(40, 120, 100),  -- สีของขอบ Dialog ที่เข้มเพื่อความชัดเจน
    DialogInput = Color3.fromRGB(30, 90, 80),  -- สีของ Input ใน Dialog ที่เข้ม
    DialogInputLine = Color3.fromRGB(100, 200, 180),  -- สีของเส้น Input ที่ชัดเจนเพื่อความโดดเด่น
    Text = Color3.fromRGB(230, 255, 240),  -- สีข้อความที่สว่างขึ้นเพื่อความชัดเจน
    SubText = Color3.fromRGB(150, 200, 180),  -- สีของ SubText ที่เข้ากับธีม
    Hover = Color3.fromRGB(80, 180, 160),  -- สีเมื่อ Hover เพื่อให้ความรู้สึกเข้มและสะดุดตา
    HoverChange = 0.06  -- การเปลี่ยนสีเมื่อ Hover ที่เด่นชัดขึ้นเล็กน้อย
}
